### ISSUE TITLE
Suggestion: Clarify the distinction between `tblite` and `xtb-python` in the README

### ISSUE THREAD

**Issue by arosen93** [grimme-lab/xtb-python#100]
As noted [here](https://github.com/grimme-lab/xtb-python/issues/99#issuecomment-1502967130), apparently `tblite` is the preferred route in terms of using a Python interface to `xtb`. This, and the overall distinction between when to use `xtb-python` vs. `tblite`, should probably be added to the README to help the user out.

**Comment by MtoLStoN** [comment]
Currently, ``xtb-python`` is no longer in active development and can be seen as more or less in maintenance mode. Therefore, I agree with using ``tblite`` as the preferred route for using ``xtb`` with Python. I will clarify this in the documentation. Thank you for bringing this to our attention.
