### ISSUE TITLE
Please add HOMO, LUMO and H-L gap in `xtb.ase.calculator`

### ISSUE THREAD

**Issue by pikakolendo02** [grimme-lab/xtb-python#103]
### Is your feature request related to a problem? Please describe.

Add attributes of fetching HOMO, LUMO and H-L gap in `xtb.ase.calculator`
### Describe the solution you'd like

Add something like `.get_homo_energy()`
### Additional context

They may be useful in machine learning projects. Thank you very much.

**Comment by awvwgk** [comment]
ASE doesn't provide a straight-forward way to export extended quantities via it's Calculator API, therefore we opted to only export the minimal set of properties which are supported by regular ASE calculators.

In general this project is not maintained anymore, and tblite is recommended as a replacement, we can consider implementing this extension in the tblite ASE calculator.
