### ISSUE TITLE
make geometric optimization in python

### ISSUE THREAD

**Issue by thegodone** [grimme-lab/xtb-python#106]
### Is your feature request related to a problem? Please describe.
can we reproduce the xtb terminal procedure into python ?  

### Describe the solution you'd like
only single point calculator is available in python code

### Describe alternatives you've considered
maybe we can have a explanation of the step of the geometric optimization step that need to be done in python or make the wrapper in python

**Comment by awvwgk** [comment]
This project is in maintenance mode, incorporating new features is currently not planned.
