### ISSUE TITLE
Will this be installed via conda?

### ISSUE THREAD

**Issue by ghutchis** [grimme-lab/xtb-python#11]
I'm a bit confused by separating the Python API into a separate repo. If I install via conda, I would normally expect the Python API to be properly installed for that conda environment. 

Will that be the case?

**Comment by awvwgk** [comment]
Yes, it will be available as `xtb-python` from conda-forge at some point, which will be marked by the first release on this repository.

The motivation for this project was to focus on a stable C-API in the `xtb` main repository (marked by the 1.0.0 API version) and allow an independent development on the Python API of `xtb`. Also I found the previous `ctypes` API rather inconvenient and it was causing a lot of support requests, the CFFI model seems superior as it does not need to be too tightly bound to the parent project.

There are a few thing I need to take care of for the conda-forge release, one is probably that they won't like repackaging `xtb` in `xtb-python`, therefore we will have a different dependency model in conda packages than currently advertised in this repository.

If you ask for a timeframe, it will probably take a little longer until my Python programming skills are sufficient to make a useful release on this project. Given the fact that I'm still learning here, any input is highly appreciated.

**Comment by awvwgk** [comment]
Just registered the `xtb-python` package on cf. It might take another moment to appear here: https://anaconda.org/conda-forge/xtb-python
