### ISSUE TITLE
cannot install xtb-python in conda

### ISSUE THREAD

**Issue by httinh123** [grimme-lab/xtb-python#117]
Hi everyone

I followed the instructions on the website to install xtb-python on conda. However I was unable to do so. An error was reported as follows:
PackagesNotFoundError: The following packages are not available from current channels: xtb-python.

Do you know how to deal with this problem?

Thank you.

**Comment by awvwgk** [comment]
`xtb-python` is now available on all supported platforms via conda-forge, including Windows/x86_64 and OSX/arm64. Closing this as resolved.
