### ISSUE TITLE
libpython3.6m.a error when building _libxtb

### ISSUE THREAD

**Issue by tangzeyuan** [grimme-lab/xtb-python#17]
I have compiled xtb sucessfully but got into troubles when creating xtb-python. 

```
(py-3.6.10) [tang@grendel-s-s81n11:xtb-python-20200604]$ meson setup build --prefix=$PWD --libdir=xtb --default-library=shared
The Meson build system
Version: 0.53.0
Source dir: /home/tang/opt/xtb/xtb-python-20200604
Build dir: /home/tang/opt/xtb/xtb-python-20200604/build
Build type: native build
Project name: xtb-python
Project version: undefined
C compiler for the host machine: cc (gcc 4.8.5 "cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)")
C linker for the host machine: cc GNU ld.bfd 2.23.52.0.1-55
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.27.1)
Run-time dependency xtb found: YES 6.3.0
Program python3 (cffi) found: YES (/home/tang/python-virtualenv/py-3.6.10/bin/python3) modules: cffi
Dependency python found: YES (pkgconfig)
Configuring _libxtb.h with command
Configuring _libxtb.c with command
Build targets in project: 2
 
Option default_library is: shared [default: static]
Found ninja-1.9.0.git.kitware.dyndep-1.jobserver-1 at /home/tang/python-virtualenv/py-3.6.10/bin/ninja
(py-3.6.10) [tang@grendel-s-s81n11:xtb-python-20200604]$ ninja -C build install
ninja: Entering directory `build'
[3/4] Linking target _libxtb.cpython-36m-x86_64-linux-gnu.so.
FAILED: _libxtb.cpython-36m-x86_64-linux-gnu.so
cc  -o _libxtb.cpython-36m-x86_64-linux-gnu.so  -Wl,--as-needed -Wl,--allow-shlib-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,_libxtb.cpython-36m-x86_64-linux-gnu.so -Wl,--whole-archive lib_libxtb.a -Wl,--no-whole-archive /home/tang/opt/xtb/xtb-python-20200604/subprojects/xtb/install/lib64/libxtb.so /comm/swstack/core/python/3.6.10/lib/libpython3.6m.a -Wl,--end-group '-Wl,-rpath,$ORIGIN/../subprojects/xtb/install/lib64' -Wl,-rpath-link,/home/tang/opt/xtb/xtb-python-20200604/build/../subprojects/xtb/install/lib64
/usr/bin/ld: /comm/swstack/core/python/3.6.10/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/comm/swstack/core/python/3.6.10/lib/libpython3.6m.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

It looks like I need to recompile python3 with -fPIC? Are there better ways to handle this?

**Comment by awvwgk** [comment]
Surprisingly, this wasn't an issue so far, but I completely agree, we need position independent code here. Could you try setting the `-fPIC` flag for the intermediate static library in the meson.build file?

```patch
diff --git a/meson.build b/meson.build
index 299013f..3596d69 100644
--- a/meson.build
+++ b/meson.build
@@ -84,6 +84,7 @@ xtb_pyext = python.extension_module(
     '_libxtb',
     xtb_cffi_srcs,
     dependencies: [xtb_dep, python_dep],
+    pic: true,
   ),
   dependencies: [xtb_dep, python_dep],
   install: true,
```

**Comment by awvwgk** [comment]
Also, GCC 4 is an ambitious choice, I would highly recommend to use at least GCC 7, better GCC 8 or newer.

**Comment by tangzeyuan** [comment]
I switched to Intel compilers and added "pic: ture" in meson.build.

> (py-3.6.3) [tang@grendel-s-s81n11:xtb-python-20200604]$ meson setup build --prefix=$PWD --libdir=xtb
> The Meson build system
> Version: 0.53.0
> Source dir: /home/tang/opt/xtb/xtb-python-20200604
> Build dir: /home/tang/opt/xtb/xtb-python-20200604/build
> Build type: native build
> Project name: xtb-python
> Project version: undefined
> C compiler for the host machine: icc (intel 18.0.2 "icc (ICC) 18.0.2 20180210")
> C linker for the host machine: icc GNU ld.bfd 2.23.52.0.1-55
> Host machine cpu family: x86_64
> Host machine cpu: x86_64
> 
> |Executing subproject xtb method meson 
> |
> |Project name: xtb
> |Project version: 6.3.0
> |Fortran compiler for the host machine: ifort (intel 18.0.2 "ifort (IFORT) 18.0.2 20180210")
> |Fortran linker for the host machine: ifort GNU ld.bfd 2.23.52.0.1-55
> |C compiler for the host machine: icc (intel 18.0.2 "icc (ICC) 18.0.2 20180210")
> |C linker for the host machine: icc GNU ld.bfd 2.23.52.0.1-55
> |Program git found: YES (/comm/swstack/tools/git/2.14.2/bin/git)
> |Program date found: YES (/usr/bin/date)
> |Program whoami found: YES (/usr/bin/whoami)
> |Program hostname found: YES (/usr/bin/hostname)
> |Configuring xtb_version.fh using configuration
> |Library mkl_rt found: YES
> |Run-time dependency OpenMP found: YES 5.0-revision1
> |Run-time dependency threads found: YES
> |Program asciidoctor found: NO
> |Build targets in project: 5
> |Subproject xtb finished.
> 
> Program python3 (cffi) found: YES (/home/tang/python-virtualenv/py-3.6.3/bin/python3) modules: cffi
> Found pkg-config: /usr/bin/pkg-config (0.27.1)
> Dependency python found: YES (pkgconfig)
> Configuring _libxtb.h with command
> Configuring _libxtb.c with command
> Build targets in project: 7
> 
> xtb-python undefined
> 
>   Subprojects                                                                                       
>     xtb: YES
> 
> Found ninja-1.9.0.git.kitware.dyndep-1.jobserver-1 at /home/tang/python-virtualenv/py-3.6.3/bin/ninja
> 
> 
> (py-3.6.3) [tang@grendel-s-s81n11:xtb-python-20200604]$ ninja -C build install
> ninja: Entering directory `build'
> [12/527] Compiling Fortran object 'subprojects/xtb/78dfbb8@@_xtb@sta/src_gfnff_gfnff_rab.f.o'.
> ../subprojects/xtb/src/gfnff/gfnff_rab.f(27): warning #5194: Source line truncated.
>       real*8 rab(nsrb)          ! output bond lengths estimates, input the predetermined bond shifts
> ------------------------------------------------------------------------^
> [101/527] Compiling Fortran object 'subprojects/xtb/78dfbb8@@_xtb@sta/src_type_options.f90.o'.
> ../subprojects/xtb/src/type/options.f90(64): warning #6380: The structure length is not a multiple of its largest element; could create misalignments for arrays of this type.   [SCC_OPTIONS]
>    type :: scc_options
> -----------^
> ../subprojects/xtb/src/type/options.f90(89): warning #6380: The structure length is not a multiple of its largest element; could create misalignments for arrays of this type.   [PEEQ_OPTIONS]
>    type :: peeq_options
> -----------^
> 
> 
> [514/527] Linking target _libxtb.cpython-36m-x86_64-linux-gnu.so.
> FAILED: _libxtb.cpython-36m-x86_64-linux-gnu.so 
> icc  -o _libxtb.cpython-36m-x86_64-linux-gnu.so  -Wl,--as-needed -Wl,--allow-shlib-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,_libxtb.cpython-36m-x86_64-linux-gnu.so -Wl,--whole-archive lib_libxtb.a -Wl,--no-whole-archive subprojects/xtb/libxtb.a subprojects/xtb/lib_xtb.a -lmkl_rt -qopenmp -pthread -lmkl_rt -qopenmp -lmkl_rt -qopenmp /comm/swstack/core/python/3.6.3/lib/libpython3.6m.a '-Wl,-rpath,$ORIGIN/subprojects/xtb' -Wl,-rpath-link,/home/tang/opt/xtb/xtb-python-20200604/build/subprojects/xtb -lifcore -limf -Wl,--end-group
> ld: /comm/swstack/core/python/3.6.3/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
> /comm/swstack/core/python/3.6.3/lib/libpython3.6m.a: could not read symbols: Bad value
> [521/527] Compiling Fortran object 'subprojects/xtb/TESTSUITE/407edbf@@xtb_test@exe/dftd4.f90.o'.
> ninja: build stopped: subcommand failed.

It looks like the problem is how python is installed.

**Comment by awvwgk** [comment]
Okay, the problem is definitely not on the `xtb-python` side.

Apparently you are trying to link Python as a static library (`/comm/swstack/core/python/3.6.3/lib/libpython3.6m.a`) into the shared module, which you shouldn't. Instead you should link against a Python shared library (maybe `/comm/swstack/core/python/3.6.3/lib/libpython3.6m.so` exist on your platform?), if you don't have a Python shared library on your system, than there is no way around updating your Python installation (I don't recommend compiling Python yourself).

Maybe it helps to explicitly not request a static dependency (see https://mesonbuild.com/Reference-manual.html#dependency) with

```patch
diff --git a/meson.build b/meson.build
index 299013f..12b8816 100644
--- a/meson.build
+++ b/meson.build
@@ -58,7 +58,7 @@ python = pymod.find_installation(
     'cffi',
   ],
 )
-python_dep = python.dependency(required: true)
+python_dep = python.dependency(required: true, static: false)
 
 # Python's CFFI is horrible in working with preprocessor statements,
 # therefore, we have to preprocess the header before passing it to the ffibuilder
```

**Comment by tangzeyuan** [comment]
Unfortunately, there is no Python shared library (libpython3.6m.so) on my platform.

I tried with `python_dep = python.dependency(required: true, static: false)` and got the same error

> [515/527] Linking target _libxtb.cpython-36m-x86_64-linux-gnu.so.
> FAILED: _libxtb.cpython-36m-x86_64-linux-gnu.so 
> icc  -o _libxtb.cpython-36m-x86_64-linux-gnu.so  -Wl,--as-needed -Wl,--allow-shlib-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,_libxtb.cpython-36m-x86_64-linux-gnu.so -Wl,--whole-archive lib_libxtb.a -Wl,--no-whole-archive subprojects/xtb/libxtb.a subprojects/xtb/lib_xtb.a -lmkl_rt -qopenmp -pthread -lmkl_rt -qopenmp -lmkl_rt -qopenmp /comm/swstack/core/python/3.6.3/lib/libpython3.6m.a '-Wl,-rpath,$ORIGIN/subprojects/xtb' -Wl,-rpath-link,/home/tang/opt/xtb/xtb-python-20200604/build/subprojects/xtb -lifcore -limf -Wl,--end-group
> ld: /comm/swstack/core/python/3.6.3/lib/libpython3.6m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
> /comm/swstack/core/python/3.6.3/lib/libpython3.6m.a: could not read symbols: Bad value
> [522/527] Compiling Fortran object 'subprojects/xtb/TESTSUITE/407edbf@@xtb_test@exe/coulomb.f90.o'.
> ninja: build stopped: subcommand failed.

**Comment by awvwgk** [comment]
To compile a shared module we have to link against a shared library or link in a PIC compiled static library, if you cannot provide those, there is no way around changing something on your local Python installation.

Not sure how much privileges you have on the machine, either ask your system operator to install a Python version which provides a shared library or install such a package yourself. An alternative is the [anaconda Python distribution](https://www.anaconda.com/), which can be installed with user privileges and certainly provides Python as a shared library.

**Comment by tangzeyuan** [comment]
Thank you for your suggestions. I will try the anaconda option.

**Comment by tangzeyuan** [comment]
Update: the installation of `xtb-python` is successful with anaconda.
