### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by jthorton** [grimme-lab/xtb-python#32]
### Is your feature request related to a problem? Please describe.
Would it be possible to add mac support on conda-forge? I know that xtb is available for mac already but I want to use it via the QCEngine interface to plug into other features like optimization with geomeTRIC and Torsiondrives and require `xtb-python`.

**Comment by awvwgk** [comment]
`xtb-python` does support OSX now, I haven't had time to put together a new release yet.

**Comment by jthorton** [comment]
Thanks for the quick response, this is great news! No rush just want to make sure it is possible.

**Comment by awvwgk** [comment]
Unfortunately, it seems like I have to look for a new CI provider for OSX testing. It worked since I last tested on Travis CI, so it should still work for now...

**Comment by jthorton** [comment]
I would recommend Github actions, at openforcefield we have recently moved most of our projects from Travis to this and it was quite painless it also still has free macOS builds! You can see the actions we run here https://github.com/openforcefield/openforcefield/actions and our yaml files which control the runs are here https://github.com/openforcefield/openforcefield/tree/master/.github/workflows I have some experience setting these up now so let me know if I can help in any way!

**Comment by awvwgk** [comment]
Just migrated (back) to GHA for OSX testing, see #36.

**Comment by awvwgk** [comment]
Seems like there won't be OSX support with 20.2 as well. Unfortunately, the `xtb` build with conda-forge is still unstable on OSX and cannot safely be used. I'll have to defer the OSX support on conda-forge to the next release of `xtb`/`xtb-python` than.

Problem is that conda-build adds the `-O3` flag, which breaks the API only on OSX.

**Comment by awvwgk** [comment]
I will track the status of C-API on OSX for conda-forge `xtb` in https://github.com/conda-forge/xtb-feedstock/issues/16

**Comment by awvwgk** [comment]
This seems to be an ABI issue for CPython 3.6 and 3.7 on OSX only, with PyPy or newer CPython versions everything works fine. See https://github.com/conda-forge/xtb-python-feedstock/pull/9.
