### ISSUE TITLE
Request: Optimization in xtb-python

### ISSUE THREAD

**Issue by retinavr** [grimme-lab/xtb-python#38]
Hello
I would like to request an optimization scheme in the python module like the xTB program itself. I know this is possible with ASE, but ASE tends to slow down things. Currently im getting a timing of 0.05 seconds for a simple linear water molecule with no angle using ASE and about 0.2 seconds for a carbon nanotube with 120 C atoms. I believe if an optimization is done without using ASE, it can run faster.
The reason for my request is that I am currently developing a VR platform for molecular simulation (scripting is done using python) and am implementing an interactive forcefield that needs a 5 step optimization to be run in approximately 0.015 seconds. If the optimization is slower, the relaxation will not be in "real-time". 
I can imagine it is possible as the xTB program already has the ability to optimize using the different methods.

Thank you
Kind regards
Zan Mahmood

**Comment by danielhollas** [comment]
@awvwgk I am very interested in this feature, is it still in the cards for this project? If so, I could take a swing at it, although I am unfamiliar with xtb and xtb-python source codes. Do you have some estimate of how much work would it be to add this?

Thanks!

Daniel Hollas
University of Bristol

**Comment by awvwgk** [comment]
This would be the best issue to start looking into: https://github.com/grimme-lab/xtb/issues/403

**Comment by awvwgk** [comment]
Since the project is in maintenance mode, there won't be any new feature added here.
