### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by sitela** [grimme-lab/xtb-python#39]
Hello,

this is not a bug report, but rather a clarification request. I would like to use the code for an MD simulation. One thing I can't understand, though, is how I can obtain the value for the energy after atomic coordinates are changed by the algorithm that implements the dynamics. I've read all the docs but only single-point calculations are described, where atomic positions are input just once upon creation of the calculator object.

In the ASE implementation the energy was a property of the molecule object, so whenever positions were changed, the energy could be recalculated accordingly. Here, however, the calculator does not seem to depend on the molecule object. Thanks!

**Comment by awvwgk** [comment]
The details are somewhat hidden in the implementation, the `xtb` C-API (in `xtb.libxtb`) provides four objects: `environment`, `molecule`, `calculator` and `results`.

While this is a good design for C and Fortran, it does not really match the Python philosophy, therefore the Python API is implementing the wrapper classes containing all relevant API objects. A `Calculator` from `xtb.interface` contains beside the `calculator` also a `molecule` and an `environment`, this allows to bundle everything in one Python object and hide the details of the C-API. This means the Python `Calculator` can also use an update to change the cartesian coordinates.

In ASE the concept is inverted, an `Atoms` object has its (ASE) `Calculator`. Therefore, the Python `Calculator` for `xtb` is wrapped in an ASE `Calculator` and the necessary checks for cache invalidation and updating of coordinates are hidden in from the user, as they should happen automatically as the `Atoms` is changed and new properties are requested.

So it largely depends on which layer you are looking, C-API, Python-API or ASE-API, they focus on different concepts, abstract different tasks and target different audiences. Depending on how you want to implement the molecular dynamics you want to use a certain abstraction layer might be more suitable for your problem than the other, but the details depend on your problem.
