### ISSUE TITLE
Multiplicity in ASE Calculator

### ISSUE THREAD

**Issue by bananenpampe** [grimme-lab/xtb-python#42]
Hello,

I am using the xtb-python ase API with open-shell systems.
I would find it more intuitively to pass the multiplicity directly to the calculator object via an instance variable like multiplicity=N as implemented for other ASE Calculators.

Kind regards

**Comment by awvwgk** [comment]
The multiplicity is determined automatically from the initial magnetic moments of the `Atoms` object.

**Comment by bananenpampe** [comment]
yes, but per default, the initial moment's list of an atoms object is a list of zeros, or the sum is 0.
what I do then is, I simply change one of the entries, but I would find it more intuitively to pass the multiplicity directly.

**Comment by awvwgk** [comment]
Due to the mutable nature of the calculator in ASE the system dependent properties should be part of the atoms object to avoid a lingering state in the calculator instance. The initial charges and initial moments seem to me like the intended way for a calculator to infer the total charge and multiplicity for an atoms object.

**Comment by bananenpampe** [comment]
okay, I haven't considered this and I definitely agree!

But now, I am wondering:
In the API, the magnetic moment is evaluated as:
`_uhf = int(self.atoms.get_initial_magnetic_moments().sum().round())`

is this the same as the number of unpaired electrons as described in the xtb documentary?
Or is this the multiplicity?

**Comment by awvwgk** [comment]
If I'm not completely mistaken this should give the number of unpaired electrons (please correct me if I screwed up the math), which is what the `xtb` API requests.

**Comment by bananenpampe** [comment]
um, so my reasoning is (don't trust my math either):
The magnetic moment is mu = sqrt(S(S+1)) where S is the sum over the magnetic moments of the unpaired electrons.
So the number of unpaired electrons should be the solution to the quadratic equation of this, divided by two.

**Comment by bananenpampe** [comment]
for S = 3/2 the formula for the _UHF for unpaired electrons only returns 2 unpaired electrons

as sqrt(1.5*(1.5+1)) is 1.9

**Comment by awvwgk** [comment]
Sorry, I can't follow this reasoning. You would calculate the multiplicity by `mult = atoms.get_initial_magnetic_moments().sum() + 1` as present in several calculators / file writers in ASE.

**Comment by bananenpampe** [comment]
that is true, I think what confused me, was the definition of the magnetic moment.
I thought about the absolute magnetic moment, so the magnitude of the S vector, while in ase the z, or (x,y,z) component is meant.

**Comment by awvwgk** [comment]
I'll close this issue as resolved then.
