### ISSUE TITLE
wanna get a function of optimization 

### ISSUE THREAD

**Issue by sym823808458** [grimme-lab/xtb-python#54]
### Is your feature request related to a problem? Please describe.
In API documentation, there is only single point calculation method. It is really helpful if the python_xtb could contain the function of opimization class.

**Comment by awvwgk** [comment]
Upstream issue https://github.com/grimme-lab/xtb/issues/403 needs to be resolved first.

**Comment by TyBalduf** [comment]
Closing this out as a duplicate of https://github.com/grimme-lab/xtb-python/issues/38
