### ISSUE TITLE
Installation of xtb from submodule broken 

### ISSUE THREAD

**Issue by kjelljorner** [grimme-lab/xtb-python#59]
Installation from git submodule xtb fails due to unrecognized meson option "static", which is referred on this line:
https://github.com/grimme-lab/xtb-python/blob/43a680be14a664aec51036ae313187b24079660d/meson.build#L47

Seems that it was broken by changes in https://github.com/grimme-lab/xtb/pull/241 so that this keyword does not longer exist. I tried to just remove that line and it seems to work, but not sure if that breaks anything further on.

**Comment by awvwgk** [comment]
Fixed by #66
