### ISSUE TITLE
parallelisation in the xtb python interface

### ISSUE THREAD

**Issue by xiki-tempula** [grimme-lab/xtb-python#65]
### Is your feature request related to a problem? Please describe.
I'm interested in using xtb python interface to run xTB calculation via QCEngine and I wish there is a way of running xTB in parallel.

### Describe the solution you'd like
```python
>>> from xtb.qcschema.harness import run_qcschema
>>> import qcelemental as qcel
>>> atomic_input = qcel.models.AtomicInput(
...     molecule = qcel.models.Molecule(
...         symbols = ["O", "H", "H"],
...         geometry = [
...             0.00000000000000,  0.00000000000000, -0.73578586109551,
...             1.44183152868459,  0.00000000000000,  0.36789293054775,
...            -1.44183152868459,  0.00000000000000,  0.36789293054775
...         ],
...     ),
...     driver = "energy",
...     model = {
...         "method": "GFN2-xTB",
...     },
...     keywords = {
...         "threads": 16,
...         "accuracy": 1.0,
...         "max_iterations": 50,
...     },
... )
```

**Comment by awvwgk** [comment]
Currently we will honor the settings from the environment variable `OMP_NUM_THREADS` in `xtb`. In principle the harness could try to set it via

```python
os.env["OMP_NUM_THREADS"] = str(input.keywords.get("threads", 1))
```

An alternative would be to create an API call in `xtb` to set this in the `TEnvironment` object. This would need a change in `xtb`, a new release of `xtb` and an update of the Python API to become available (i.e. more a long-term solution).

**Comment by xiki-tempula** [comment]
Thanks.
