### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jthorton** [grimme-lab/xtb-python#85]
### Is your feature request related to a problem? Please describe.
Would it be possible to have a new release of xtb-python and upload it to conda-forge with some of the new features?  This fix https://github.com/grimme-lab/xtb-python/pull/74 would be very helpful in particular.

**Comment by jthorton** [comment]
Just wanted to highlight this again incase it was missed cc @awvwgk

**Comment by awvwgk** [comment]
I guess this is not really my responsibility anymore after I left the Grimme group. I was hoping somebody would find to take over (see #76), but I guess I can draft another release after the change to the build system (see #95).
