### ISSUE TITLE
configure fails to find xtb because it only uses pkgconfig (with -Ddefault_library=shared)

### ISSUE THREAD

**Issue by yurivict** [grimme-lab/xtb-python#92]
When configured with ```-Ddefault_library=shared``` it fails to find xtb:
```
The Meson build system
Version: 0.63.2
Source dir: /disk-samsung/freebsd-ports/science/py-xtb/work/xtb-python-20.2-11-g3335421
Build dir: /disk-samsung/freebsd-ports/science/py-xtb/work/xtb-python-20.2-11-g3335421/_build
Build type: native build
Project name: xtb-python
Project version: undefined
C compiler for the host machine: cc (clang 14.0.5 "FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)")
C linker for the host machine: cc ld.lld 14.0.5
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/local/bin/pkg-config (1.8.0)
Found CMake: /usr/local/bin/cmake (3.24.3)
Run-time dependency xtb found: NO (tried pkgconfig)
Looking for a fallback subproject for the dependency xtb

meson.build:33:2: ERROR: Subproject exists but has no meson.build file
```

This is because xtb doesn't install pkgconfig files, and meson doesn't try cmake for some reason.

Additionally, it shouldn't use subprojects when configured with ```-Ddefault_library=shared``` because then xtb is externally installed.

**Comment by awvwgk** [comment]
Please build xtb with meson to use it with the Python API.

**Comment by awvwgk** [comment]
Without further details there is not much what can be done on this issue. Using the meson build of xtb is preferred, however meson should be able to find xtb built with CMake, if not this issue is probably not on the xtb side but on the distro packaged meson.
